// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package stdio

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type stdioEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	PidTgid     uint64
	UidGid      uint64
	ReqLen      uint64
	CgroupId    uint64
	DataLen     uint64
	Fd          uint64
	Rw          uint8
	Data        [131072]uint8
	Comm        [16]int8
	_           [7]byte
}

type stdioInflightRead struct {
	_     structs.HostLayout
	Buf   uint64
	Count uint64
	Fd    uint64
}

// loadStdio returns the embedded CollectionSpec for stdio.
func loadStdio() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_StdioBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load stdio: %w", err)
	}

	return spec, err
}

// loadStdioObjects loads stdio and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*stdioObjects
//	*stdioPrograms
//	*stdioMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadStdioObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadStdio()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// stdioSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stdioSpecs struct {
	stdioProgramSpecs
	stdioMapSpecs
	stdioVariableSpecs
}

// stdioProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stdioProgramSpecs struct {
	TracepointEnterRead  *ebpf.ProgramSpec `ebpf:"tracepoint_enter_read"`
	TracepointEnterWrite *ebpf.ProgramSpec `ebpf:"tracepoint_enter_write"`
	TracepointExitRead   *ebpf.ProgramSpec `ebpf:"tracepoint_exit_read"`
}

// stdioMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stdioMapSpecs struct {
	FakeEventMap *ebpf.MapSpec `ebpf:"_fake_event_map"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	Inflight     *ebpf.MapSpec `ebpf:"inflight"`
}

// stdioVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type stdioVariableSpecs struct {
}

// stdioObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadStdioObjects or ebpf.CollectionSpec.LoadAndAssign.
type stdioObjects struct {
	stdioPrograms
	stdioMaps
	stdioVariables
}

func (o *stdioObjects) Close() error {
	return _StdioClose(
		&o.stdioPrograms,
		&o.stdioMaps,
	)
}

// stdioMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadStdioObjects or ebpf.CollectionSpec.LoadAndAssign.
type stdioMaps struct {
	FakeEventMap *ebpf.Map `ebpf:"_fake_event_map"`
	Events       *ebpf.Map `ebpf:"events"`
	Inflight     *ebpf.Map `ebpf:"inflight"`
}

func (m *stdioMaps) Close() error {
	return _StdioClose(
		m.FakeEventMap,
		m.Events,
		m.Inflight,
	)
}

// stdioVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadStdioObjects or ebpf.CollectionSpec.LoadAndAssign.
type stdioVariables struct {
}

// stdioPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadStdioObjects or ebpf.CollectionSpec.LoadAndAssign.
type stdioPrograms struct {
	TracepointEnterRead  *ebpf.Program `ebpf:"tracepoint_enter_read"`
	TracepointEnterWrite *ebpf.Program `ebpf:"tracepoint_enter_write"`
	TracepointExitRead   *ebpf.Program `ebpf:"tracepoint_exit_read"`
}

func (p *stdioPrograms) Close() error {
	return _StdioClose(
		p.TracepointEnterRead,
		p.TracepointEnterWrite,
		p.TracepointExitRead,
	)
}

func _StdioClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed stdio_x86_bpfel.o
var _StdioBytes []byte
