// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package tcpconn

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tcpconnConnectMeta struct {
	_        structs.HostLayout
	PidTgid  uint64
	UidGid   uint64
	CgroupId uint64
	Comm     [16]int8
}

// loadTcpconn returns the embedded CollectionSpec for tcpconn.
func loadTcpconn() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcpconnBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tcpconn: %w", err)
	}

	return spec, err
}

// loadTcpconnObjects loads tcpconn and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tcpconnObjects
//	*tcpconnPrograms
//	*tcpconnMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTcpconnObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTcpconn()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tcpconnSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnSpecs struct {
	tcpconnProgramSpecs
	tcpconnMapSpecs
	tcpconnVariableSpecs
}

// tcpconnProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnProgramSpecs struct {
	TraceTcpClose     *ebpf.ProgramSpec `ebpf:"trace_tcp_close"`
	TraceTcpSetState  *ebpf.ProgramSpec `ebpf:"trace_tcp_set_state"`
	TraceTcpV4Connect *ebpf.ProgramSpec `ebpf:"trace_tcp_v4_connect"`
	TraceTcpV6Connect *ebpf.ProgramSpec `ebpf:"trace_tcp_v6_connect"`
}

// tcpconnMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnMapSpecs struct {
	Events          *ebpf.MapSpec `ebpf:"events"`
	InflightConnect *ebpf.MapSpec `ebpf:"inflight_connect"`
}

// tcpconnVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tcpconnVariableSpecs struct {
}

// tcpconnObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnObjects struct {
	tcpconnPrograms
	tcpconnMaps
	tcpconnVariables
}

func (o *tcpconnObjects) Close() error {
	return _TcpconnClose(
		&o.tcpconnPrograms,
		&o.tcpconnMaps,
	)
}

// tcpconnMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnMaps struct {
	Events          *ebpf.Map `ebpf:"events"`
	InflightConnect *ebpf.Map `ebpf:"inflight_connect"`
}

func (m *tcpconnMaps) Close() error {
	return _TcpconnClose(
		m.Events,
		m.InflightConnect,
	)
}

// tcpconnVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnVariables struct {
}

// tcpconnPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTcpconnObjects or ebpf.CollectionSpec.LoadAndAssign.
type tcpconnPrograms struct {
	TraceTcpClose     *ebpf.Program `ebpf:"trace_tcp_close"`
	TraceTcpSetState  *ebpf.Program `ebpf:"trace_tcp_set_state"`
	TraceTcpV4Connect *ebpf.Program `ebpf:"trace_tcp_v4_connect"`
	TraceTcpV6Connect *ebpf.Program `ebpf:"trace_tcp_v6_connect"`
}

func (p *tcpconnPrograms) Close() error {
	return _TcpconnClose(
		p.TraceTcpClose,
		p.TraceTcpSetState,
		p.TraceTcpV4Connect,
		p.TraceTcpV6Connect,
	)
}

func _TcpconnClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tcpconn_x86_bpfel.o
var _TcpconnBytes []byte
