// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type readCallInfo struct {
	_       structs.HostLayout
	BufAddr uint64
	Len     uint64
}

type readEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	ReqLen      uint64
	PidTgid     uint64
	UidGid      uint64
	SslPtr      uint64
	DataLen     uint32
	Rw          uint8
	Comm        [16]int8
	Data        [16384]uint8
	_           [3]byte
}

// loadRead returns the embedded CollectionSpec for read.
func loadRead() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ReadBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load read: %w", err)
	}

	return spec, err
}

// loadReadObjects loads read and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*readObjects
//	*readPrograms
//	*readMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadReadObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRead()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// readSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type readSpecs struct {
	readProgramSpecs
	readMapSpecs
	readVariableSpecs
}

// readProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type readProgramSpecs struct {
	ProbeSslReadEntry   *ebpf.ProgramSpec `ebpf:"probe_ssl_read_entry"`
	ProbeSslReadExExit  *ebpf.ProgramSpec `ebpf:"probe_ssl_read_ex_exit"`
	ProbeSslReadExit    *ebpf.ProgramSpec `ebpf:"probe_ssl_read_exit"`
	ProbeSslWriteExExit *ebpf.ProgramSpec `ebpf:"probe_ssl_write_ex_exit"`
	ProbeSslWriteExit   *ebpf.ProgramSpec `ebpf:"probe_ssl_write_exit"`
}

// readMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type readMapSpecs struct {
	FakeEventMap *ebpf.MapSpec `ebpf:"_fake_event_map"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	StartMap     *ebpf.MapSpec `ebpf:"start_map"`
}

// readVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type readVariableSpecs struct {
}

// readObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadReadObjects or ebpf.CollectionSpec.LoadAndAssign.
type readObjects struct {
	readPrograms
	readMaps
	readVariables
}

func (o *readObjects) Close() error {
	return _ReadClose(
		&o.readPrograms,
		&o.readMaps,
	)
}

// readMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadReadObjects or ebpf.CollectionSpec.LoadAndAssign.
type readMaps struct {
	FakeEventMap *ebpf.Map `ebpf:"_fake_event_map"`
	Events       *ebpf.Map `ebpf:"events"`
	StartMap     *ebpf.Map `ebpf:"start_map"`
}

func (m *readMaps) Close() error {
	return _ReadClose(
		m.FakeEventMap,
		m.Events,
		m.StartMap,
	)
}

// readVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadReadObjects or ebpf.CollectionSpec.LoadAndAssign.
type readVariables struct {
}

// readPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadReadObjects or ebpf.CollectionSpec.LoadAndAssign.
type readPrograms struct {
	ProbeSslReadEntry   *ebpf.Program `ebpf:"probe_ssl_read_entry"`
	ProbeSslReadExExit  *ebpf.Program `ebpf:"probe_ssl_read_ex_exit"`
	ProbeSslReadExit    *ebpf.Program `ebpf:"probe_ssl_read_exit"`
	ProbeSslWriteExExit *ebpf.Program `ebpf:"probe_ssl_write_ex_exit"`
	ProbeSslWriteExit   *ebpf.Program `ebpf:"probe_ssl_write_exit"`
}

func (p *readPrograms) Close() error {
	return _ReadClose(
		p.ProbeSslReadEntry,
		p.ProbeSslReadExExit,
		p.ProbeSslReadExit,
		p.ProbeSslWriteExExit,
		p.ProbeSslWriteExit,
	)
}

func _ReadClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed read_x86_bpfel.o
var _ReadBytes []byte
