// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type sslCallInfo struct {
	_       structs.HostLayout
	BufAddr uint64
	Len     uint64
}

type sslEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	ReqLen      uint64
	PidTgid     uint64
	UidGid      uint64
	SslPtr      uint64
	DataLen     uint32
	Rw          uint8
	Comm        [16]int8
	Data        [16384]uint8
	_           [3]byte
}

// loadSsl returns the embedded CollectionSpec for ssl.
func loadSsl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SslBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ssl: %w", err)
	}

	return spec, err
}

// loadSslObjects loads ssl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sslObjects
//	*sslPrograms
//	*sslMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSslObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSsl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sslSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslSpecs struct {
	sslProgramSpecs
	sslMapSpecs
	sslVariableSpecs
}

// sslProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslProgramSpecs struct {
	ProbeSslReadEntry    *ebpf.ProgramSpec `ebpf:"probe_ssl_read_entry"`
	ProbeSslReadExExit   *ebpf.ProgramSpec `ebpf:"probe_ssl_read_ex_exit"`
	ProbeSslReadExit     *ebpf.ProgramSpec `ebpf:"probe_ssl_read_exit"`
	ProbeSslWriteEntry   *ebpf.ProgramSpec `ebpf:"probe_ssl_write_entry"`
	ProbeSslWriteExEntry *ebpf.ProgramSpec `ebpf:"probe_ssl_write_ex_entry"`
}

// sslMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslMapSpecs struct {
	FakeEventMap *ebpf.MapSpec `ebpf:"_fake_event_map"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	StartMap     *ebpf.MapSpec `ebpf:"start_map"`
}

// sslVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslVariableSpecs struct {
}

// sslObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslObjects struct {
	sslPrograms
	sslMaps
	sslVariables
}

func (o *sslObjects) Close() error {
	return _SslClose(
		&o.sslPrograms,
		&o.sslMaps,
	)
}

// sslMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslMaps struct {
	FakeEventMap *ebpf.Map `ebpf:"_fake_event_map"`
	Events       *ebpf.Map `ebpf:"events"`
	StartMap     *ebpf.Map `ebpf:"start_map"`
}

func (m *sslMaps) Close() error {
	return _SslClose(
		m.FakeEventMap,
		m.Events,
		m.StartMap,
	)
}

// sslVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslVariables struct {
}

// sslPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslPrograms struct {
	ProbeSslReadEntry    *ebpf.Program `ebpf:"probe_ssl_read_entry"`
	ProbeSslReadExExit   *ebpf.Program `ebpf:"probe_ssl_read_ex_exit"`
	ProbeSslReadExit     *ebpf.Program `ebpf:"probe_ssl_read_exit"`
	ProbeSslWriteEntry   *ebpf.Program `ebpf:"probe_ssl_write_entry"`
	ProbeSslWriteExEntry *ebpf.Program `ebpf:"probe_ssl_write_ex_entry"`
}

func (p *sslPrograms) Close() error {
	return _SslClose(
		p.ProbeSslReadEntry,
		p.ProbeSslReadExExit,
		p.ProbeSslReadExit,
		p.ProbeSslWriteEntry,
		p.ProbeSslWriteExEntry,
	)
}

func _SslClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ssl_x86_bpfel.o
var _SslBytes []byte
