# OpenSSL: https://docs.openssl.org/1.1.1/man3/SSL_read/
# GnuTLS: https://www.gnutls.org/manual/gnutls.html#gnutls_005frecord_005fsend-1

# WARNING: tetragon doesn't support uretprobe, so we can not get the plaintext
# from the SSL_read/SSL_read_ex.

apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "tls-plaintext"
spec:
  uprobes:
  - path: "/lib64/libssl.so.3"  # fedora
    message: "read_ex"
    symbols:
    - "SSL_read_ex"
    args:
    - index: 1
      type: "char_buf"
      maxData: true
      returnCopy: true
      sizeArgIndex: 3
    - index: 2
      type: "uint32"
    tags:
    - "tls.read.ex"
  - path: "/lib64/libssl.so.3"  # fedora
    message: "read"
    symbols:
    - "SSL_read"
    args:
    - index: 1
      type: "char_buf"
      maxData: true
      returnCopy: true
      sizeArgIndex: 3
    - index: 2
      type: "int32"
    tags:
    - "tls.read"
  - path: "/lib64/libssl.so.3"  # fedora
    message: "write_ex"
    symbols:
    - "SSL_write_ex"
    args:
    - index: 1
      type: "char_buf"
      maxData: true
      sizeArgIndex: 3
    - index: 2
      type: "uint32"
    tags:
    - "tls.write.ex"
  - path: "/lib64/libssl.so.3"  # fedora
    message: "write"
    symbols:
    - "SSL_write"
    args:
    - index: 1
      type: "char_buf"
      maxData: true
      sizeArgIndex: 3
    - index: 2
      type: "int32"
    tags:
    - "tls.write"
