// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package execve

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type execDynlib struct {
	_        structs.HostLayout
	Fd       uint64
	PidTgid  uint64
	Comm     [16]int8
	Filename [256]int8
}

type execExecValue struct {
	_    structs.HostLayout
	Proc execProc
	Args [2048]int8
}

type execOpenKey struct {
	_       structs.HostLayout
	Fd      int64
	PidTgid uint64
}

type execOpenValue struct {
	_        structs.HostLayout
	Filename [256]int8
}

type execProc struct {
	_                 structs.HostLayout
	TimestampNs       uint64
	StartTimeNs       uint64
	ParentStartTimeNs uint64
	Pid               int32
	Ppid              int32
	OldPid            int32
	Comm              [16]int8
	Filename          [256]int8
	ArgsLen           uint32
	ArgsTruncated     uint8
	_                 [7]byte
}

// loadExec returns the embedded CollectionSpec for exec.
func loadExec() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExecBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load exec: %w", err)
	}

	return spec, err
}

// loadExecObjects loads exec and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*execObjects
//	*execPrograms
//	*execMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExecObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExec()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// execSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execSpecs struct {
	execProgramSpecs
	execMapSpecs
	execVariableSpecs
}

// execProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execProgramSpecs struct {
	TracepointSchedProcessExec *ebpf.ProgramSpec `ebpf:"tracepoint_sched_process_exec"`
	TracepointSysEnterClose    *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_close"`
	TracepointSysEnterMmap     *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_mmap"`
	TracepointSysEnterOpenat   *ebpf.ProgramSpec `ebpf:"tracepoint_sys_enter_openat"`
	TracepointSysExitOpenat    *ebpf.ProgramSpec `ebpf:"tracepoint_sys_exit_openat"`
}

// execMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execMapSpecs struct {
	FakeDynlibMap *ebpf.MapSpec `ebpf:"_fake_dynlib_map"`
	FakeProcMap   *ebpf.MapSpec `ebpf:"_fake_proc_map"`
	DynlibEvents  *ebpf.MapSpec `ebpf:"dynlib_events"`
	ExecHeap      *ebpf.MapSpec `ebpf:"exec_heap"`
	InflightMmap  *ebpf.MapSpec `ebpf:"inflight_mmap"`
	InflightOpen  *ebpf.MapSpec `ebpf:"inflight_open"`
	ProcEvents    *ebpf.MapSpec `ebpf:"proc_events"`
}

// execVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type execVariableSpecs struct {
}

// execObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type execObjects struct {
	execPrograms
	execMaps
	execVariables
}

func (o *execObjects) Close() error {
	return _ExecClose(
		&o.execPrograms,
		&o.execMaps,
	)
}

// execMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type execMaps struct {
	FakeDynlibMap *ebpf.Map `ebpf:"_fake_dynlib_map"`
	FakeProcMap   *ebpf.Map `ebpf:"_fake_proc_map"`
	DynlibEvents  *ebpf.Map `ebpf:"dynlib_events"`
	ExecHeap      *ebpf.Map `ebpf:"exec_heap"`
	InflightMmap  *ebpf.Map `ebpf:"inflight_mmap"`
	InflightOpen  *ebpf.Map `ebpf:"inflight_open"`
	ProcEvents    *ebpf.Map `ebpf:"proc_events"`
}

func (m *execMaps) Close() error {
	return _ExecClose(
		m.FakeDynlibMap,
		m.FakeProcMap,
		m.DynlibEvents,
		m.ExecHeap,
		m.InflightMmap,
		m.InflightOpen,
		m.ProcEvents,
	)
}

// execVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type execVariables struct {
}

// execPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExecObjects or ebpf.CollectionSpec.LoadAndAssign.
type execPrograms struct {
	TracepointSchedProcessExec *ebpf.Program `ebpf:"tracepoint_sched_process_exec"`
	TracepointSysEnterClose    *ebpf.Program `ebpf:"tracepoint_sys_enter_close"`
	TracepointSysEnterMmap     *ebpf.Program `ebpf:"tracepoint_sys_enter_mmap"`
	TracepointSysEnterOpenat   *ebpf.Program `ebpf:"tracepoint_sys_enter_openat"`
	TracepointSysExitOpenat    *ebpf.Program `ebpf:"tracepoint_sys_exit_openat"`
}

func (p *execPrograms) Close() error {
	return _ExecClose(
		p.TracepointSchedProcessExec,
		p.TracepointSysEnterClose,
		p.TracepointSysEnterMmap,
		p.TracepointSysEnterOpenat,
		p.TracepointSysExitOpenat,
	)
}

func _ExecClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed exec_x86_bpfel.o
var _ExecBytes []byte
