// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package sslsniff

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type boringCallInfo struct {
	_       structs.HostLayout
	BufAddr uint64
	Len     uint64
	SslPtr  uint64
}

type boringEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	PidTgid     uint64
	UidGid      uint64
	CgroupId    uint64
	SslPtr      uint64
	ReqLen      uint64
	DataLen     uint64
	Rw          uint8
	Comm        [16]int8
	Data        [65536]uint8
	_           [7]byte
}

// loadBoring returns the embedded CollectionSpec for boring.
func loadBoring() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BoringBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load boring: %w", err)
	}

	return spec, err
}

// loadBoringObjects loads boring and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*boringObjects
//	*boringPrograms
//	*boringMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBoringObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBoring()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// boringSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type boringSpecs struct {
	boringProgramSpecs
	boringMapSpecs
	boringVariableSpecs
}

// boringProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type boringProgramSpecs struct {
	ProbeBoringSslReadEntry *ebpf.ProgramSpec `ebpf:"probe_boring_ssl_read_entry"`
	ProbeBoringSslReadExit  *ebpf.ProgramSpec `ebpf:"probe_boring_ssl_read_exit"`
	ProbeBoringSslWriteExit *ebpf.ProgramSpec `ebpf:"probe_boring_ssl_write_exit"`
}

// boringMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type boringMapSpecs struct {
	FakeEventMap *ebpf.MapSpec `ebpf:"_fake_event_map"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	StartMap     *ebpf.MapSpec `ebpf:"start_map"`
}

// boringVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type boringVariableSpecs struct {
}

// boringObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBoringObjects or ebpf.CollectionSpec.LoadAndAssign.
type boringObjects struct {
	boringPrograms
	boringMaps
	boringVariables
}

func (o *boringObjects) Close() error {
	return _BoringClose(
		&o.boringPrograms,
		&o.boringMaps,
	)
}

// boringMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBoringObjects or ebpf.CollectionSpec.LoadAndAssign.
type boringMaps struct {
	FakeEventMap *ebpf.Map `ebpf:"_fake_event_map"`
	Events       *ebpf.Map `ebpf:"events"`
	StartMap     *ebpf.Map `ebpf:"start_map"`
}

func (m *boringMaps) Close() error {
	return _BoringClose(
		m.FakeEventMap,
		m.Events,
		m.StartMap,
	)
}

// boringVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBoringObjects or ebpf.CollectionSpec.LoadAndAssign.
type boringVariables struct {
}

// boringPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBoringObjects or ebpf.CollectionSpec.LoadAndAssign.
type boringPrograms struct {
	ProbeBoringSslReadEntry *ebpf.Program `ebpf:"probe_boring_ssl_read_entry"`
	ProbeBoringSslReadExit  *ebpf.Program `ebpf:"probe_boring_ssl_read_exit"`
	ProbeBoringSslWriteExit *ebpf.Program `ebpf:"probe_boring_ssl_write_exit"`
}

func (p *boringPrograms) Close() error {
	return _BoringClose(
		p.ProbeBoringSslReadEntry,
		p.ProbeBoringSslReadExit,
		p.ProbeBoringSslWriteExit,
	)
}

func _BoringClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed boring_x86_bpfel.o
var _BoringBytes []byte
