// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package sslsniff

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type rustlsCallInfo struct {
	_       structs.HostLayout
	BufAddr uint64
	SslPtr  uint64
}

type rustlsEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	PidTgid     uint64
	UidGid      uint64
	SslPtr      uint64
	ReqLen      uint64
	DataLen     uint64
	Rw          uint8
	Comm        [16]int8
	Data        [65536]uint8
	_           [7]byte
}

// loadRustls returns the embedded CollectionSpec for rustls.
func loadRustls() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_RustlsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load rustls: %w", err)
	}

	return spec, err
}

// loadRustlsObjects loads rustls and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*rustlsObjects
//	*rustlsPrograms
//	*rustlsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadRustlsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadRustls()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// rustlsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rustlsSpecs struct {
	rustlsProgramSpecs
	rustlsMapSpecs
	rustlsVariableSpecs
}

// rustlsProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rustlsProgramSpecs struct {
	ProbeRustlsTokioPollReadEntry  *ebpf.ProgramSpec `ebpf:"probe_rustls_tokio_poll_read_entry"`
	ProbeRustlsTokioPollReadExit   *ebpf.ProgramSpec `ebpf:"probe_rustls_tokio_poll_read_exit"`
	ProbeRustlsTokioPollWriteEntry *ebpf.ProgramSpec `ebpf:"probe_rustls_tokio_poll_write_entry"`
}

// rustlsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rustlsMapSpecs struct {
	FakeEventMap *ebpf.MapSpec `ebpf:"_fake_event_map"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	ReadInfo     *ebpf.MapSpec `ebpf:"read_info"`
}

// rustlsVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type rustlsVariableSpecs struct {
}

// rustlsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadRustlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type rustlsObjects struct {
	rustlsPrograms
	rustlsMaps
	rustlsVariables
}

func (o *rustlsObjects) Close() error {
	return _RustlsClose(
		&o.rustlsPrograms,
		&o.rustlsMaps,
	)
}

// rustlsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadRustlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type rustlsMaps struct {
	FakeEventMap *ebpf.Map `ebpf:"_fake_event_map"`
	Events       *ebpf.Map `ebpf:"events"`
	ReadInfo     *ebpf.Map `ebpf:"read_info"`
}

func (m *rustlsMaps) Close() error {
	return _RustlsClose(
		m.FakeEventMap,
		m.Events,
		m.ReadInfo,
	)
}

// rustlsVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadRustlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type rustlsVariables struct {
}

// rustlsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadRustlsObjects or ebpf.CollectionSpec.LoadAndAssign.
type rustlsPrograms struct {
	ProbeRustlsTokioPollReadEntry  *ebpf.Program `ebpf:"probe_rustls_tokio_poll_read_entry"`
	ProbeRustlsTokioPollReadExit   *ebpf.Program `ebpf:"probe_rustls_tokio_poll_read_exit"`
	ProbeRustlsTokioPollWriteEntry *ebpf.Program `ebpf:"probe_rustls_tokio_poll_write_entry"`
}

func (p *rustlsPrograms) Close() error {
	return _RustlsClose(
		p.ProbeRustlsTokioPollReadEntry,
		p.ProbeRustlsTokioPollReadExit,
		p.ProbeRustlsTokioPollWriteEntry,
	)
}

func _RustlsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed rustls_x86_bpfel.o
var _RustlsBytes []byte
