// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package postgres

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type pgConnKey struct {
	_       structs.HostLayout
	PidTgid uint64
	Fd      uint64
}

type pgEvent struct {
	_           structs.HostLayout
	TimestampNs uint64
	PidTgid     uint64
	UidGid      uint64
	ReqLen      uint64
	CgroupId    uint64
	DataLen     uint64
	Fd          uint64
	MsgType     uint8
	Data        [16384]uint8
	Comm        [16]int8
	_           [7]byte
}

// loadPg returns the embedded CollectionSpec for pg.
func loadPg() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PgBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pg: %w", err)
	}

	return spec, err
}

// loadPgObjects loads pg and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pgObjects
//	*pgPrograms
//	*pgMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPgObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPg()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pgSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgSpecs struct {
	pgProgramSpecs
	pgMapSpecs
	pgVariableSpecs
}

// pgProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgProgramSpecs struct {
	TracepointEnterClose  *ebpf.ProgramSpec `ebpf:"tracepoint_enter_close"`
	TracepointEnterSendto *ebpf.ProgramSpec `ebpf:"tracepoint_enter_sendto"`
}

// pgMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgMapSpecs struct {
	FakeEventMap *ebpf.MapSpec `ebpf:"_fake_event_map"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	Inflight     *ebpf.MapSpec `ebpf:"inflight"`
}

// pgVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgVariableSpecs struct {
}

// pgObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPgObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgObjects struct {
	pgPrograms
	pgMaps
	pgVariables
}

func (o *pgObjects) Close() error {
	return _PgClose(
		&o.pgPrograms,
		&o.pgMaps,
	)
}

// pgMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPgObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgMaps struct {
	FakeEventMap *ebpf.Map `ebpf:"_fake_event_map"`
	Events       *ebpf.Map `ebpf:"events"`
	Inflight     *ebpf.Map `ebpf:"inflight"`
}

func (m *pgMaps) Close() error {
	return _PgClose(
		m.FakeEventMap,
		m.Events,
		m.Inflight,
	)
}

// pgVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPgObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgVariables struct {
}

// pgPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPgObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgPrograms struct {
	TracepointEnterClose  *ebpf.Program `ebpf:"tracepoint_enter_close"`
	TracepointEnterSendto *ebpf.Program `ebpf:"tracepoint_enter_sendto"`
}

func (p *pgPrograms) Close() error {
	return _PgClose(
		p.TracepointEnterClose,
		p.TracepointEnterSendto,
	)
}

func _PgClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pg_x86_bpfel.o
var _PgBytes []byte
