name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/collector.yml'
      - 'collector/**.go'
      - 'collector/Makefile'
      - 'collector/go.**'
      - 'collector/**.c'
      - 'collector/**.h'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/collector.yml'
      - 'collector/**.go'
      - 'collector/Makefile'
      - 'collector/go.**'
      - 'collector/**.c'
      - 'collector/**.h'
  merge_group:
  workflow_dispatch:

jobs:

  build:
    defaults:
      run:
        working-directory: ./collector
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: stable

    - name: LLVM
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://apt.llvm.org/llvm.sh | sudo bash -s -- 20
        sudo ln -s /usr/bin/llvm-strip-20 /usr/bin/llvm-strip

    - name: Build
      run: make build

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8

    - name: Lint
      run: make lint
