name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/collector.yml'
      - 'collector/**.go'
      - 'collector/Makefile'
      - 'collector/go.**'
      - 'collector/**.c'
      - 'collector/**.h'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/collector.yml'
      - 'collector/**.go'
      - 'collector/Makefile'
      - 'collector/go.**'
      - 'collector/**.c'
      - 'collector/**.h'
  merge_group:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version for the docker image'
        required: true
        type: string

jobs:

  build:
    defaults:
      run:
        working-directory: ./collector
    runs-on: ubuntu-latest
    env:
      BUILDER: ghcr.io/kemingy/ebpf-builder:0.1.0
    steps:
    - uses: actions/checkout@v6

    - name: Build
      run: docker run --rm -v "$PWD":/workspace -w /workspace $BUILDER bash -c "make build && make lint-ebpf"

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        working-directory: ./collector

    - name: Lint
      run: make lint-go

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/watchu-collector
        flavor: |
          latest=false
        tags: |
          type=semver,pattern={{version}},value=${{ inputs.version }}

    - name: Build and push images
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        provenance: false  # avoid push manifest-list
        file: ./collector/Dockerfile
        context: ./collector
