name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/frontend.yml'
      - 'frontend/**'
  merge_group:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version for the docker image'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v6

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/watchu-frontend
        flavor: |
          latest=false
        tags: |
          type=semver,pattern={{version}},value=${{ inputs.version }}

    - name: Build and push images
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        provenance: false  # avoid push manifest-list
        file: ./frontend/Dockerfile
        context: ./frontend
        target: prod
