name: Go Gateway

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/gateway.yml'
      - 'gateway/**.go'
      - 'gateway/Makefile'
      - 'gateway/go.**'
      - 'gateway/db/**'
      - 'gateway/atlas.hcl'
      - 'gateway/docker-compose.yaml'
      - 'gateway/sqlc.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/gateway.yml'
      - 'gateway/**.go'
      - 'gateway/Makefile'
      - 'gateway/go.**'
      - 'gateway/db/**'
      - 'gateway/atlas.hcl'
      - 'gateway/docker-compose.yaml'
      - 'gateway/sqlc.yaml'
  merge_group:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version for the docker image'
        required: true
        type: string

jobs:

  build:
    env:
      DATABASE_URL: postgres://watchu:watchu@localhost:5432/watchu?sslmode=disable
    defaults:
      run:
        working-directory: ./gateway
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: watchu
          POSTGRES_USER: watchu
          POSTGRES_PASSWORD: watchu
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U watchu -d watchu"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: stable

    - name: Set up Atlas CLI
      uses: ariga/setup-atlas@v0
    
    - name: Verify schema drift
      run: atlas migrate validate --env dev --dir "file://db/migrations" --dev-url $DATABASE_URL

    - name: Deploy Atlas Migrations
      run: atlas migrate apply --env dev --dir "file://db/migrations" --url $DATABASE_URL

    - name: Build
      run: make build

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        working-directory: ./gateway

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v6

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository_owner }}/watchu-gateway
        flavor: |
          latest=false
        tags: |
          type=semver,pattern={{version}},value=${{ inputs.version }}

    - name: Build and push images
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        provenance: false  # avoid push manifest-list
        file: ./gateway/Dockerfile
        context: ./gateway
