name: Go Gateway

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/gateway.yml'
      - 'gateway/**.go'
      - 'gateway/Makefile'
      - 'gateway/go.**'
      - 'gateway/db/**'
      - 'gateway/atlas.hcl'
      - 'gateway/docker-compose.yaml'
      - 'gateway/sqlc.yaml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/gateway.yml'
      - 'gateway/**.go'
      - 'gateway/Makefile'
      - 'gateway/go.**'
      - 'gateway/db/**'
      - 'gateway/atlas.hcl'
      - 'gateway/docker-compose.yaml'
      - 'gateway/sqlc.yaml'
  merge_group:
  workflow_dispatch:

jobs:

  build:
    env:
      DATABASE_URL: postgres://watchu:watchu@localhost:5432/watchu?sslmode=disable
    defaults:
      run:
        working-directory: ./gateway
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_DB: watchu
          POSTGRES_USER: watchu
          POSTGRES_PASSWORD: watchu
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U watchu -d watchu"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: stable

    - name: Set up Atlas CLI
      uses: ariga/setup-atlas@v0
    
    - name: Verify schema drift
      run: atlas migrate validate --env dev --dir "file://db/migrations" --dev-url $DATABASE_URL

    - name: Deploy Atlas Migrations
      run: atlas migrate apply --env dev --dir "file://db/migrations" --url $DATABASE_URL

    - name: Build
      run: make build

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v9.2.1
      with:
        working-directory: ./gateway
