name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
      - '**.go'
      - 'Makefile'
      - 'go.**'
      - '**.c'
      - '**.h'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**'
      - '**.go'
      - 'Makefile'
      - 'go.**'
      - '**.c'
      - '**.h'
  merge_group:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: stable

    - name: Build
      run: make build

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8

    - name: Lint
      run: make lint
